[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt"
  functions = "infra/netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.11"

[[plugins]]
  package = "@netlify/plugin-python"

[functions]
  directory = "infra/netlify/functions"
  node_bundler = "none"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true
